### ISSUE TITLE
Frontend optimizations

### ISSUE THREAD

**Issue by janjonas** [weweave/DnnDevTools#12]
* Minimize JavaScript in overlay (for example angular.js)
* Use SASS, jsHint, jscs (and integrate them into the build processes)

**Comment by mbenfer** [comment]
I tried to move all JS code into dnn.js, but only the code from HostSettings worked out. When I try to move the JS from Overlay.aspx, angular is missing. When I try to move the JS from Toolbar.html, $.connection is undefined.

**Comment by janjonas** [comment]
Improved JavaScript include order and moved JavaScript for toolbar to dnn.js.
dnn.js won't work for overlay, created new issue for this improvement, see #17
