### ISSUE TITLE
"Select log level" dropdown shows incorrect value

### ISSUE THREAD

**Issue by janjonas** [weweave/DnnDevTools#15]
Change "Select log level" dropdown to "Error" and load page Host > DNN Dev Tools:  "Select log level" dropdown shows "ALL" instead of "Error"

**Comment by mbenfer** [comment]
I don't get what you mean. Which dropdown should shows what? :D

**Comment by janjonas** [comment]
Works as expected ...

**Comment by janjonas** [comment]
Reopen: Shouldn't we need to use selectedIndex?

**Comment by mbenfer** [comment]
I don't know what you mean by selectedIndex and stuff... the initial value for the log level has never been set. Now the log level will be set at page load like that:

logLevelSelect.value = window.weweave.dnnDevTools.logMessageTraceLevel;
