### ISSUE TITLE
Add description text for each section (Mail Catch, DNN Event tracing, Log message tracing) on host settings page

### ISSUE THREAD

**Issue by janjonas** [weweave/DnnDevTools#20]

**Comment by mbenfer** [comment]
Give me texts and I add them ;)

**Comment by weweave** [comment]
Description texts are added to the resource file (keys: DnnEventTraceDescription, LogMessageTraceDescription, MailCatchDescription).

**Comment by janjonas** [comment]
Description texts are added to the resource file (keys: DnnEventTraceDescription, LogMessageTraceDescription, MailCatchDescription).
