### ISSUE TITLE
Detail view for all notifications (mails, DNN events, log messages)

### ISSUE THREAD

**Issue by janjonas** [weweave/DnnDevTools#7]

**Comment by mbenfer** [comment]
Added all detail views very roughly. Implementing design tomorrow.

**Comment by mbenfer** [comment]
In order to show the detail page without loading the whole stream I need a detail-service for DnnEvent and LogMessage as well.

**Comment by janjonas** [comment]
API implemented.

**Comment by mbenfer** [comment]
Detail views generally available - design enhancements to come
