### ISSUE TITLE
Overlay behind DNN popups

### ISSUE THREAD

**Issue by janjonas** [weweave/DnnDevTools#9]
Test page http://localhost/dnndevtools/Admin/User-Accounts and click on "add user".

**Comment by mbenfer** [comment]
By overlay you mean the tooltip? If yes, I moved it on z-index: 32-bit integer (2147483647) :D

**Comment by janjonas** [comment]
No, overlay :)
![overlay](https://cloud.githubusercontent.com/assets/1097370/12276732/a52bb142-b977-11e5-8080-89a8d7df189c.png)

**Comment by mbenfer** [comment]
fixed
